/* Generated By:JavaCC: Do not edit this line. practica2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface practica2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPC = 1;
  /** RegularExpression Id. */
  int COM = 2;
  /** RegularExpression Id. */
  int WHILE = 3;
  /** RegularExpression Id. */
  int ENDWHILE = 4;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int ENDIF = 6;
  /** RegularExpression Id. */
  int THEN = 7;
  /** RegularExpression Id. */
  int ELSEIF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int PRINT = 10;
  /** RegularExpression Id. */
  int READ = 11;
  /** RegularExpression Id. */
  int DO = 12;
  /** RegularExpression Id. */
  int OPAR = 13;
  /** RegularExpression Id. */
  int CPAR = 14;
  /** RegularExpression Id. */
  int FOR = 15;
  /** RegularExpression Id. */
  int NUM = 16;
  /** RegularExpression Id. */
  int ID = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPC>",
    "<COM>",
    "\"while\"",
    "\"endwhile\"",
    "\"if\"",
    "\"endif\"",
    "\"then\"",
    "\"elseif\"",
    "\"else\"",
    "\"print\"",
    "\"read\"",
    "\"do\"",
    "\"(\"",
    "\")\"",
    "\"for\"",
    "<NUM>",
    "<ID>",
    "\";\"",
    "\"from\"",
    "\"to\"",
    "\"{\"",
    "\"}\"",
    "\"by\"",
    "\"<:\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
