/* Generated By:JavaCC: Do not edit this line. practica2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface practica2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPC = 1;
  /** RegularExpression Id. */
  int COM = 2;
  /** RegularExpression Id. */
  int WHILE = 3;
  /** RegularExpression Id. */
  int ENDWHILE = 4;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int ENDIF = 6;
  /** RegularExpression Id. */
  int THEN = 7;
  /** RegularExpression Id. */
  int ELSEIF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int PRINT = 10;
  /** RegularExpression Id. */
  int NUM = 11;
  /** RegularExpression Id. */
  int ID = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPC>",
    "<COM>",
    "\"while\"",
    "\"endwhile\"",
    "\"if\"",
    "\"endif\"",
    "\"then\"",
    "\"elseif\"",
    "\"else\"",
    "\"print\"",
    "<NUM>",
    "<ID>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
